// Reads images from public/images/ and converts to base64 data URLs
// Run this before rendering: node scripts/encode-images.js
const fs = require('fs');
const path = require('path');

const imagesDir = path.join(__dirname, '../public/images');
const outputFile = path.join(__dirname, '../src/image-data.js');

const imageNames = [
  'scene-01-scroll',
  'scene-02-jerusalem',
  'scene-03-spain',
  'scene-04-westafrica',
  'scene-05-maps',
  'scene-06-slavery',
];

const extensions = ['.png', '.jpg', '.jpeg', '.webp'];

let output = '// Auto-generated by scripts/encode-images.js — do not edit manually\n';
output += 'export const IMAGES = {\n';

let found = 0;
let missing = 0;

for (const name of imageNames) {
  let data = null;
  let mimeType = 'image/jpeg';

  for (const ext of extensions) {
    const filePath = path.join(imagesDir, name + ext);
    if (fs.existsSync(filePath)) {
      const buffer = fs.readFileSync(filePath);
      data = buffer.toString('base64');
      mimeType = ext === '.png' ? 'image/png' : ext === '.webp' ? 'image/webp' : 'image/jpeg';
      console.log(`  ✓ Found: ${name}${ext}`);
      found++;
      break;
    }
  }

  if (data) {
    output += `  '${name}': 'data:${mimeType};base64,${data}',\n`;
  } else {
    output += `  '${name}': null,\n`;
    console.log(`  ✗ Missing: ${name} (will show dark background)`);
    missing++;
  }
}

output += '};\n';

fs.writeFileSync(outputFile, output);
console.log(`\nDone! ${found} images encoded, ${missing} missing.`);
console.log(`Saved to: src/image-data.js`);
